# Generated by Django 5.2.8 on 2025-11-28 00:56

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="invoice_url",
            field=models.URLField(
                blank=True,
                db_index=True,
                help_text="URL to the generated PDF invoice",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="id",
            field=models.UUIDField(
                db_index=True,
                default=uuid.uuid4,
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="reference",
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
    ]
