# Generated by Django 5.2.8 on 2025-11-18 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userverification',
            name='verification_code',
            field=models.CharField(max_length=255),
        ),
    ]
