# Generated by Django 5.2.8 on 2025-11-28 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_remove_user_role_user_country_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="is_premium",
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
