# Generated by Django 5.2.8 on 2025-11-30 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0002_alter_poll_poll_id_alter_pollcategory_category_id"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="polloption",
            options={"ordering": ["index"]},
        ),
        migrations.AddField(
            model_name="polloption",
            name="index",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterUniqueTogether(
            name="polloption",
            unique_together={("poll", "index")},
        ),
    ]
